#pragma once

namespace ASCII {
  
class Lines {
public:
  typedef enum {
    LINE_UNIMPLEMENTED,
    LINE_OK,
    LINE_BACK,
    LINE_ON,
    LINE_OFF,
    LINE_XFLIP,
    LINE_YFLIP,
    LINE_DFLIP,
    LINE_INVERT_COLORS,
    LINE_EYEDROPPER,
    LINE_AFFECT_CHARS,
    LINE_AFFECT_FG,
    LINE_AFFECT_BG,
    LINE_QUICKSAVE,
    LINE_PALETTE_SCROLL,
    LINE_SWAP_COLORS,
    LINE_FILE_SAVE,
    LINE_FILE_OPEN,
    LINE_LOAD_CHARSET,
    LINE_LOAD_PALETTE,
    LINE_SETTINGS,
    LINE_HINTS,
    LINE_TOGGLE_BACKUPS,
    LINE_TOGGLE_HOLD,
    LINE_TOGGLE_WIRELESS,
    LINE_TOGGLE_HINTS,
    LINE_FILES_UP_LEVEL,
    LINE_FILES_NEW,
    LINE_FILES_NEXT_PAGE,
    LINE_FILES_PREV_PAGE,
    LINE_STATUS_SAVED,
    LINE_STATUS_LOADED,
    LINE_STATUS_CHARSET,
    LINE_STATUS_PALETTE,
    LINE_LINECOUNT,
  } LINE;
  
  static const char* english[LINE_LINECOUNT];
};

}

